# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
set_msg_config  -ruleid {1}  -string {{LCD_CONTROLLER}}  -suppress 
set_msg_config  -ruleid {2}  -id {filemgmt 20-1763}  -suppress 
set_msg_config  -ruleid {3}  -id {Synth 8-3295}  -new_severity {ERROR} 
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/lab28/verilog_lab/project/vivado/Bicycle_computer/Bicycle_computer.cache/wt [current_project]
set_property parent.project_path /home/lab28/verilog_lab/project/vivado/Bicycle_computer/Bicycle_computer.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/lab28/verilog_lab/project/sources/top_of_your_bicycle.v
  /home/lab28/verilog_lab/project/sources/dual2bcd.v
  /home/lab28/verilog_lab/project/sources/bcd2ascii.v
  /home/lab28/verilog_lab/project/sources/distance.v
  /home/lab28/verilog_lab/project/sources/syn/timing.v
  /home/lab28/verilog_lab/project/sources/syn/clk_divider.v
  /home/lab28/verilog_lab/project/sources/syn/global_toplevel.v
  /home/lab28/verilog_lab/project/sources/syn/pulse_shape.v
  /home/lab28/verilog_lab/project/sources/syn/kmh_test.v
}
read_vhdl -library xil_defaultlib /home/lab28/verilog_lab/project/sources/syn/LCD_Controller.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/lab28/verilog_lab/project/sources/syn/timings.xdc
set_property used_in_implementation false [get_files /home/lab28/verilog_lab/project/sources/syn/timings.xdc]

read_xdc /home/lab28/verilog_lab/project/sources/syn/stop_watch.xdc
set_property used_in_implementation false [get_files /home/lab28/verilog_lab/project/sources/syn/stop_watch.xdc]


synth_design -top timing -part xc7z010clg400-1


write_checkpoint -force -noxdef timing.dcp

catch { report_utilization -file timing_utilization_synth.rpt -pb timing_utilization_synth.pb }
